### PR TITLE
Added Pawn stars to TVRage exceptions.txt

### PR DESCRIPTION
**Pull request by neoatomic**
On TVRage the show is called Pawn Star$. But Scene name is Pawn Stars.
http://www.tvrage.com/pawn-star

### CODE REVIEW

**Comment by neoatomic** [comment]
@miigotu Have you rights to approve the commits here.?

**Comment by miigotu** [comment]
Yes, done.

**Comment by neoatomic** [comment]
@miigotu For some reason the exceptions are not being added to SR.
To make it even more strange, it seems that exceptions from thexem.de are being added.?
(The scene name "Die Drei vom Pfandhaus" i can only find on theexem.de http://thexem.de/xem/show/1759 )

So i'm wondering if the TVRage exceptions are being overwritten by those of theexem.de ?

sr

**Comment by miigotu** [comment]
I am considering adding the exception text files directly to the repo, because there have been some problems for some people getting the scene exceptions from their repos.

You have your info set to that language?

**Comment by neoatomic** [comment]
No. The exception is for German. I use Dutch language. (So that is wrong and risks getting downloads with the wrong language.)

**Comment by miigotu** [comment]
had to merge master->gh-pages

**Comment by miigotu** [comment]
@fernandog can you set the default branch for both exceptions repos to gh-pages please?

**Comment by fernandog** [comment]
@miigotu done

**Pull request merged**
